#!/bin/bash

# KAIRO QUANTUM - Deployment Commands
# Copy and run these commands to deploy

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  RAILWAY BACKEND DEPLOYMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Login to Railway:"
echo "   railway login"
echo ""
echo "2. Create new project (or link existing):"
echo "   railway init"
echo ""
echo "3. Add PostgreSQL database:"
echo "   railway add --database postgresql"
echo ""
echo "4. Copy DATABASE_URL from Railway dashboard and add to environment variables"
echo ""
echo "5. Add all environment variables from backend/.env.production to Railway dashboard"
echo "   Railway Dashboard → Your Project → Variables → Add all variables"
echo ""
echo "6. Deploy backend:"
echo "   railway up"
echo ""
echo "7. Add custom domain in Railway:"
echo "   Railway Dashboard → Settings → Networking → Custom Domain"
echo "   Domain: api.kairoquantum.com"
echo ""
echo "8. Run database migrations:"
echo "   railway run npx prisma migrate deploy"
echo "   railway run npx prisma generate"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  VERCEL FRONTEND DEPLOYMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Login to Vercel:"
echo "   vercel login"
echo ""
echo "2. Deploy to production:"
echo "   vercel --prod"
echo ""
echo "3. Add environment variables in Vercel Dashboard:"
echo "   Vercel Dashboard → Project → Settings → Environment Variables"
echo "   Add all variables from .env.production"
echo ""
echo "4. Add custom domains:"
echo "   Vercel Dashboard → Project → Settings → Domains"
echo "   Add: kairoquantum.com"
echo "   Add: www.kairoquantum.com"
echo ""
echo "5. Redeploy with environment variables:"
echo "   vercel --prod"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  DNS CONFIGURATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Add these DNS records at your domain registrar or Cloudflare:"
echo ""
echo "Type   | Name | Target                    | Proxy"
echo "-------|------|---------------------------|-------"
echo "CNAME  | www  | cname.vercel-dns.com      | Yes"
echo "CNAME  | @    | cname.vercel-dns.com      | Yes"
echo "CNAME  | api  | [your-app].railway.app    | Yes"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  STRIPE CONFIGURATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Create products in Stripe Dashboard:"
echo "   - Pro Monthly: \$49/month"
echo "   - Pro Annual: \$490/year"
echo "   - Enterprise: \$199/month"
echo ""
echo "2. Update .env.production with Price IDs"
echo ""
echo "3. Configure webhook:"
echo "   URL: https://api.kairoquantum.com/api/webhooks/stripe"
echo "   Events: checkout.session.completed, customer.subscription.*"
echo ""
echo "4. Enable Stripe Tax:"
echo "   Stripe Dashboard → Settings → Tax → Enable"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
